@startuml be1
actor User
boundary "Request Intake" as Intake
control "Experts Process Management Controller" as Controller
control "Experts Service" as Service
control "Point Algorithm Expert" as Algorithm
activate User
activate Intake
activate Controller
activate Service
activate Algorithm

alt User fills inputs
    User -> Intake: Fill in Drop Down Menus
    User -> Intake: Enter a deal guess
    User -> Intake: Press "Submit"
    Intake -> Controller: Request valuation
    Controller -> Service: Request point system evaluation
    Service -> Algorithm: Request point calculation
    Algorithm -> Algorithm: Calculate points
    Algorithm --> Service: Return point calculation
    Service -> Service: Form point system evaluation
    Service --> Controller: Return point system evaluation
    Controller -> Controller: Compile results
    Controller --> Intake: Sends results
    Intake --> User: Display results and indicate correctness
else User does not fill inputs
    User -> Intake: Attempt submission
    Intake --> User: Display error and guidelines
end

alt Internet connection lost
    Intake -> User: Show error page and recommend retry
end

@enduml
