@startuml
actor User
boundary "Request Intake"
control "Experts Process Management Controller"
control "Experts Service"
control "Point Algorithm Expert"
boundary "External API Service Expert"
boundary "AI Expert"

activate User
activate "Request Intake"
activate "Experts Process Management Controller"
activate "Experts Service"
activate "Point Algorithm Expert"
activate "External API Service Expert"
activate "AI Expert"

alt "User Fills inputs"
User ->  "Request Intake": Fill in Drop Down Menus
User ->  "Request Intake": Fill in Text Input
User ->  "Request Intake": Fill in Image Input
User -> "Request Intake": Enter a Deal Guess
User -> "Request Intake": Press "Submit"
"Request Intake" -> "Experts Process Management Controller": Request Valuation
"Experts Process Management Controller" -> "Experts Service": Request point sytem evaluation
"Experts Process Management Controller" -> "Experts Service": Request external API system evaluation
"Experts Process Management Controller" -> "Experts Service": Request AI expert evaluation
"Experts Service"-> "Point Algorithm Expert": Request point calculation
"Point Algorithm Expert" -> "Point Algorithm Expert": Calculate points
"Experts Service"<-- "Point Algorithm Expert": Return point calculation
"Experts Service" -> "Experts Service": Form point system evaluation
"Experts Process Management Controller" <-- "Experts Service": Return point sytem evaluation


"Experts Service"-> "External API Service Expert": Request API value lookup
"External API Service Expert" -> "External API Service Expert": Get API value
"Experts Service"<-- "External API Service Expert": Return API value
"Experts Service" -> "Experts Service": Form API system evaluation
"Experts Process Management Controller" <-- "Experts Service": Return external API system evaluation

"Experts Service"-> "AI Expert": Request AI response
"AI Expert" -> "AI Expert": Compute AI response
"Experts Service"<-- "AI Expert": Return AI response
"Experts Service" -> "Experts Service": Form AI system evaluation
"Experts Process Management Controller" <-- "Experts Service": Return AI expert evaluation

"Experts Process Management Controller" -> "Experts Process Management Controller": compile results

"Request Intake" <-- "Experts Process Management Controller": send result

User <-- "Request Intake": Display results and indicat correctness
else "User does not fill inputs"
User -> "Request Intake": Attempt submission
User <-- "Request Intake": Display error and guidelines

end

alt "Internet connection lost"
User <- "Request Intake": Show error page and recommend retry
end


@enduml