@startuml be4
participant User
participant "Request Car Depreciation Curve"
participant "Car Recommendation Service"
participant "Request Information"
participant "Extended AI Service"

activate User
activate "Request Car Depreciation Curve"
activate "Car Recommendation Service"
activate "Request Information"
activate "Extended AI Service"

User -> "Request Car Depreciation Curve": Request depreciation curve for existing deal
"Request Car Depreciation Curve" -> "Car Recommendation Service": Transfer user request
"Car Recommendation Service" -> "Request Information": Request information of existing deal

alt User has a previous deal valuation
    "Car Recommendation Service" <-- "Request Information": Return information of existing deal
    "Car Recommendation Service" -> "Extended AI Service": Request depreciation curve calculation
    "Extended AI Service" -> "Extended AI Service": Compute Depreciation Curve
    "Car Recommendation Service" <-- "Extended AI Service": Return depreciation curve calculation
    "Car Recommendation Service" -> "Car Recommendation Service": Compile result
    "Car Recommendation Service" -> User: Display result
else User does not have an existing deal valuation
    "Car Recommendation Service" <-- "Request Information": Return error message
    User <-- "Car Recommendation Service": Display Error message
end

@enduml
