@startuml be8

participant User
participant Registration
participant "Account Management"
participant "Account Information"

activate User
activate "Account Management"
activate Registration
activate "Account Information"

User -> Registration: Enter credentials
Registration -> "Account Management": Request account creation
"Account Management" -> "Account Information": Validate credentials

alt User does not have an existing account
    "Account Information" --> "Account Management": Return success message
    "Account Management" -> "Account Management": Create account
    "Account Management" -> "Account Information": Request to save credentials
    "Account Information" -> "Account Information": Save credentials
    "Account Management" <-- "Account Information": Return success message
    "Account Management" --> "Registration": Return account
    "Registration" --> User: Display success message
else User already has an account
    "Account Management" <-- "Account Information": Return error message
    "Account Management" --> "Registration": Return error message
    "Registration" --> User: Display error message
end

@enduml
