@startuml be9

participant User
participant "Login"
participant "Account Management"
participant "Account Information"

activate User
activate "Login"
activate "Account Management"
activate "Account Information"

User -> "Login": Enter Username & Password
User -> "Login": Press "Login"
"Login" -> "Account Management": Request login
"Account Management" -> "Account Information": Validate credentials

alt User enters correct credentials
    "Account Information" --> "Account Management": Return valid result
    "Account Management" --> "Login": Return success response
    "Login" --> User: Grant access & display homepage
else User enters incorrect credentials
    "Account Information" --> "Account Management": Return invalid result
    "Account Management" --> "Login": Return failure response
    "Login" --> User: Display login error
else Internet connection lost
    "Login" -> User: Show error page and recommend retry
end

@enduml
